SimpleProject/urls.py
from django.contrib import admin
from django.urls import path
from SimpleApp01 import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.showTrainee),
    path('save',views.saveTrainee),
    path('edit/<int:id>',views.editTrainee),
    path('delete/<int:id>',views.deleteTrainee),
    path('update/<int:id>',views.updateTrainee),
    path('export/pdf/', views.export_to_pdf, name='export_to_pdf'),
    path('export/excel/', views.export_to_excel, name='export_to_excel'),
]

SimpleApp01/models.py
from django.db import models

# Create your models here.
class Trainee(models.Model):
    TraineeId = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=30)
    ContactNo = models.CharField(max_length=15)
    ContactAddress = models.CharField(max_length=100)
    EmailAddress = models.EmailField()  
    BatchNo = models.CharField(max_length=30 , default="N\A")

    class Meta:
        db_table="Trainee"

SimpleApp01/forms.py
from django import forms
from .models import Trainee

class TraineeForm(forms.ModelForm):
    class Meta:
        model = Trainee
        fields= "__all__"
    

SimpleApp01/views.py
from django.shortcuts import render,redirect
from .models import * 
from .forms import *
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import pandas as pd
import io
from reportlab.lib import colors

# Create your views here.
def showTrainee(request):
    trainees = Trainee.objects.all()
    return render(request,"show.html",{'trainees':trainees})
    
def saveTrainee(request):
    if request.method == 'POST':
      form = TraineeForm(request.POST)
      if form.is_valid():
        try:
            form.save()
            return redirect("/")
        except:
            pass 
      else:
        pass
    
    else:
        form = TraineeForm()
        
    return render(request,"trainee.html",{'form':form})    
    
def deleteTrainee(request,id):
    trainee = Trainee.objects.get(TraineeId = id)
    trainee.delete()
    return redirect('/')


def editTrainee(request,id):
    trainee = Trainee.objects.get(TraineeId = id) 
    return render(request,"edit.html",{'trainee':trainee})
    
       
def updateTrainee(request,id):
      trainee = Trainee.objects.get(TraineeId = id)           
      form = TraineeForm(request.POST , instance = trainee)
      if form.is_valid():
            form.save()
            return redirect("/")
      return render(request,"edit.html",{'trainee':trainee})
    


# myapp/views.py-----normal---- PDF 


# def export_to_pdf(request):
#     response = HttpResponse(content_type='application/pdf')
#     response['Content-Disposition'] = 'attachment; filename="data.pdf"'

#     buffer = io.BytesIO()
#     p = canvas.Canvas(buffer, pagesize=letter)
    
#     data = Trainee.objects.all().values('Name', 'ContactNo','ContactAddress','EmailAddress','BatchNo')
    
#     y = 750
#     for item in data:
#         p.drawString(100, y, f"{item['Name']} - {item['ContactNo']} -  {item['ContactAddress']} - {item['EmailAddress']} - {item['BatchNo']}")
#         y -= 20

#     p.showPage()
#     p.save()
    
#     pdf = buffer.getvalue()
#     buffer.close()
#     response.write(pdf)
    
#     return response

def export_to_excel(request):
    data = Trainee.objects.all().values('Name', 'ContactNo','ContactAddress','EmailAddress','BatchNo')
    df = pd.DataFrame(list(data))

    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename="data.xlsx"'
    
    df.to_excel(response, index=False)
    
    return response
        

# myapp/views.py------table wise---PDF


def export_to_pdf(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="data.pdf"'

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)

    data = Trainee.objects.all().values('Name', 'ContactNo','ContactAddress','EmailAddress','BatchNo')
    data_list = list(data)
    
    if not data_list:
        p.drawString(100, 700, "No data available.")
        p.showPage()
        p.save()
        pdf = buffer.getvalue()
        buffer.close()
        response.write(pdf)
        return response
    
    
    # Set table position
    x = 50
    y = 700
    row_height = 20
    col_width = [150, 100, 200, 100, 100]  # Define column widths for each column
    
    p.setFont("Helvetica-Bold", 12)
    headers = ["Name", "ContactNo", "ContactAddress", "EmailAddress", "BatchNo"]
    for i, header in enumerate(headers):
        p.drawString(x + sum(col_width[:i]), y, header)
    y -= row_height

    # # Draw table header
    # p.setFont("Helvetica-Bold", 12)
    # p.drawString(x, y, "Name")
    # p.drawString(x + col_width[0], y, "ContactNo")
    # p.drawString(x + col_width[0] + col_width[1], y, "ContactAddress")
    # p.drawString(x + col_width[0] + col_width[1] + col_width[2], y, "EmailAddress")
    # p.drawString(x + col_width[0] + col_width[1] + col_width[2] + col_width[3], y, "BatchNo")
     
    # y -= row_height

    # Draw header border
    p.setStrokeColor(colors.black)
    p.line(x, y + row_height, x + sum(col_width), y + row_height)

    # Reset font for data rows
    p.setFont("Helvetica", 12)

    for item in data:
        p.drawString(x, y, item['Name'])
        p.drawString(x + col_width[0], y, str(item['ContactNo']))
        p.drawString(x + col_width[0] + col_width[1], y, item['ContactAddress'])
        p.drawString(x + col_width[0] + col_width[1] + col_width[2], y,(item['EmailAddress']))
        p.drawString(x + col_width[0] + col_width[1] + col_width[2] + col_width[3], y, str(item['BatchNo']))
        
        y -= row_height

        # Draw row border
        p.line(x, y + row_height, x + sum(col_width), y + row_height)

    # Draw bottom border
    p.line(x, y + row_height, x + sum(col_width), y + row_height)

    p.showPage()
    p.save()

    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)

    return response
        

SimpleApp01/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
     <!-- Latest compiled and minified CSS -->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Trainee</title>
</head>
<body>
  <div class="row bg-secondary">
    <div class="container col-md-6 col-md-offset-3">
      <div class="m-5 p-5 bg-info-subtle rounded">
          <div class="bg-primary rounded">
              <h2 class="text-center p-3 text-white">Edit Your Information</h2>
          </div>
          <div class="container">
            
                <form method="POST" class="post-form" action ="/update/{{trainee.TraineeId}}" >
                  {% csrf_token %}
                  <div class="container">

                      <div class="form-group">
                        <label for="exampleInputName2"> Trainee ID</label>
                        <input type="text" name="TraineeId" class="form-control" id="id_Traineeid" value="{{trainee.TraineeId}}" readonly>
                      </div>
          
                      <div class="form-group">
                        <label for="exampleInputName2"> Trainee Name</label>
                        <input type="text" name="Name" class="form-control" id="id_Name" value="{{trainee.Name}}">
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName2">Contact No</label>
                        <input type="text" name="ContactNo" class="form-control" id="id_ContactNo" value="{{trainee.ContactNo}}">
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName2">Contact Address</label>
                        <input type="text" name="ContactAddress" class="form-control" id="id_ContactAddress" value="{{trainee.ContactAddress}}">
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName2">Email Address</label>
                        <input type="email" name="EmailAddress" class="form-control" id="id_EmailAddress" value="{{trainee.EmailAddress}}">
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName2">Batch No.</label>
                        <input type="text" name="BatchNo" class="form-control" id="id_EmailAddress" value="{{trainee.BatchNo}}">
                      </div>
                      
                      <div>
                        <button class="btn btn-warning mt-3 btn-lg text-white"  type="submit">Update</button>
                        <a href="/" class="btn btn-primary btn-lg mt-3 mx-3 ">Back</a>
                      </div>
                      
                     
                     
                  </div>
              </form>
          </div>

      </div>
     

  </div>

  </div>
   
   
   
</body>
</html>

SimpleApp01/templates/editproblem.html
<form method="POST" class="post-form"  action="/update/{{trainee.TraineeId}}">
    {% csrf_token %}
    <div class="mb-3">
      <label for="TraineeId" class="form-label">Trainee ID</label>
      <input type="text" class="form-control" id="TraineeId" aria-describedby="" value="{{trainee.TraineeId}}" readonly>
    </div>
    <div class="mb-3">
        <label for="Name" class="form-label">Trainee Name</label>
        <input type="text" class="form-control" id="Name" aria-describedby="" value="{{trainee.Name}}">
      </div>
      <div class="mb-3">
        <label for="EmailAddress" class="form-label">Email address</label>
        <input type="email" class="form-control" id="EmailAddress" aria-describedby="emailHelp" value="{{trainee.EmailAddress}}">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
      </div>
      <div class="mb-3">
        <label for="ContactNo" class="form-label">Contact NO.</label>
        <input type="text" class="form-control" id="ContactNo" aria-describedby="" value="{{trainee.ContactNo}}">
      </div>
      <div class="mb-3">
        <label for="ContactAddress" class="form-label">Contact Address</label>
        <input type="text" class="form-control" id="ContactAddress" aria-describedby="" value="{{trainee.ContactAddress}}">
      </div>
      <div class="mb-3">
        <label for="BatchNo" class="form-label">Batch NO.</label>
        <input type="text" class="form-control" id="BatchNo" aria-describedby="" value="{{trainee.BatchNo}}">
      </div>
    <button type="submit" class="btn btn-warning">Update</button>
  </form> 

SimpleApp01/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Show trainee</title>
</head>
<body>
   
        
        <div class="m-5">
            <div class="bg-success p-2">
                <h3 class="text-center text-white">Trainee Information</h3>
        
            </div>
            
           <div >
            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                      <!--  <th>Trainee ID</th>---->
                        <th>Name</td>
                        <th>Contact Number</th>
                        <th>Contact Address</th>
                        <th>Email Address</th>
                        <th>Batch Number</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                          {%for trn in trainees%}
        
                          <tr>
                           
                            <td>{{trn.Name}}</td>
                            <td>{{trn.ContactNo}}</td>
                            <td>{{trn.ContactAddress}}</td>
                            <td>{{trn.EmailAddress}}</td>
                            <td>{{trn.BatchNo}}</td>
                            <td>
                              <a href="/edit/{{trn.TraineeId}}" class="btn btn-warning text-white">Edit</a>
                              <a href="/delete/{{trn.TraineeId}}" class="btn btn-danger">Delete</a>
                            </td>
        
                          </tr>
        
                          {% endfor %}
                </tbody>
                
            </table>

            <center>
              <a href="/save" class="btn btn-primary btn-lg m-4">Add New Trainee</a>
              <a href="/export/pdf/" class="btn btn-danger btn-lg m-4">Download PDF</a>
              <a href="/export/excel/" class="btn btn-success btn-lg m-4">Download Excel File</a>
            </center>
            
        
            </div>
    
        </div>
   
    
    
    
   
   
   
</body>
</html>

SimpleApp01/templates/trainee.html
<!DOCTYPE html>
<html lang="en">
<head>
      <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Save Trainee</title>
</head>
<body>
    <div class="row  bg-info ">
        <div class=" container col-md-6 col-md-offset-3">
            <div class="m-5 p-5 bg-secondary bg-gradient rounded">
                <form method="POST" action ="save" >
                    {% csrf_token %}
                    <div>
                        <div class="bg-success rounded">
                            <lable></lable>
                            <div>
                                <h3 class="text-white p-3">Enter Trainee Information</h3>
                            </div>
                        </div>
            
                        <div>
                            <lable class="text-white">Trainee Name </lable>
                            <div>
                                {{form.Name}}
                            </div>
                        </div>
                        <div>
                            <lable class="text-white">ContactNo</lable>
                            <div>
                                {{form.ContactNo}}
                            </div>
                        </div>
                        <div>
                            <lable class="text-white">ContactAddress</lable>
                            <div>
                                {{form.ContactAddress}}
                            </div>
                        </div>
                        <div>
                            <lable class="text-white">EmailAddress</lable>
                            <div>
                                {{form.EmailAddress}}
                            </div>
                        </div>
                        <div>
                            <lable class="text-white"> BatchNo</lable>
                            <div>
                                {{form.BatchNo}}
                            </div>
                        </div>
                        <div >
                            <lable></lable>
                            <div>
                                <button class="btn btn-success mt-3 btn-lg"  type="submit">Save</button>
                            </div>
                        </div>
                       
                       
                    </div>
                </form>

            </div>
            

        </div>

    </div>
    
   
    
</body>
</html>